server:
  port: 9998

eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_SERVER_ADDRESS:localhost}:9000/eureka/
  instance:
    prefer-ip-address: true


spring:
  application:
    name: config

  cloud:
    config:
      server:
        git:
          uri: ${CONFIG_SERVER_ADDRESS:https://gitee.com/luoshangcai/spring-cloud-config.git}
          username: ${CONFIG_SERVER_USERNAME:luoshangcai}
          password: ${CONFIG_SERVER_PASSWORD:lsc5360.0}
          search-paths: ${CONFIG_SERVER_FOLDER:study}

#management:
#  endpoint:
#    shutdown:
#      enabled: true
#  endpoints:
#    web:
#      exposure:
#        include:
#          - shutdown